### ISSUE TITLE
EVAC 'Total Energy Consumed' Unknown

### ISSUE THREAD

**Issue by fbradyirl** [TypQxQ/HACS-Sigenergy-Local-Modbus#17]
<img width="1449" alt="Image" src="https://github.com/user-attachments/assets/9cd2b64e-1573-4f00-b9e0-d1277f62d8fd" />

The Sigen AC Charger works well except the `sensor.sigen_ac_charger_total_energy_consumed` sensor has always an unknown state.

It worked ok using the older package yaml config:

```yaml
      - name: Sigen AC Charger - Total energy consumed
        unique_id: sigenac_total_energy_consumed
        device_address: !secret sigen_ac_modbus_slave
        address: 32001
        input_type: input
        data_type: uint32
        precision: 1
        unit_of_measurement: kWh
        device_class: energy
        state_class: total
        scale: 0.01
        scan_interval: 60
```

but im unsure how that maps to the new HACS code here.
